"use client"

import { createContext, useContext, useState, ReactNode } from "react"

export type Lang = "en" | "ru" | "kz"

type LangContextType = {
  lang: Lang
  setLang: (l: Lang) => void
  t: (key: string) => string
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Nav
    "nav.universities": "Universities",
    "nav.services": "Services",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.cart": "Wishlist",

    // Hero
    "hero.badge": "Your Gateway to Kazakhstan",
    "hero.title1": "Study in",
    "hero.title2": "Kazakhstan",
    "hero.subtitle": "We handle everything — admission, visa, dormitory, and settling into your new city. You focus on studying.",
    "hero.apply": "Apply Now for Free",
    "hero.learnMore": "Learn More",

    // Trust indicators
    "trust.partner": "Official University Partners",
    "trust.support": "Full Support — Visa to Dorm",
    "trust.consultation": "Free Consultation",
    "trust.process": "End-to-End Process",

    // Why Kazakhstan
    "whykz.badge": "Why Kazakhstan?",
    "whykz.title": "A Smart Choice for International Students",
    "whykz.subtitle": "Affordable, English-taught degrees at globally recognised universities — with a safe and welcoming environment.",
    "whykz.section.title": "Why Study in Kazakhstan?",
    "whykz.section.subtitle": "Experience a fusion of world-class education and breathtaking Central Asian culture at a fraction of the cost.",
    "whykz.international.title": "International Recognition",
    "whykz.international.desc": "Degrees recognized globally through the Bologna Process, opening doors to careers in Europe, Asia, and beyond.",
    "whykz.affordable.title": "Affordable Tuition",
    "whykz.affordable.desc": "Premium education starting from $2,000/year. High quality of life at half the cost of Western universities.",
    "whykz.english.title": "English-Taught Programs",
    "whykz.english.desc": "No language barrier. Hundreds of programs available in English across IT, Medicine, and Business.",
    "whykz.vibrant.title": "Vibrant Student Life",
    "whykz.vibrant.desc": "From the ski resorts of Almaty to the futuristic architecture of Astana. A truly global student hub.",
    "whykz.safe.title": "Safe & Welcoming",
    "whykz.safe.desc": "Kazakhstan consistently ranks among the safest countries for international students in Central Asia.",
    "whykz.career.title": "Career Opportunities",
    "whykz.career.desc": "A booming economy and growing startup scene offer real career prospects after graduation.",

    // Benefits (Why EduPath)
    "benefits.badge": "Why EduPath?",
    "benefits.title": "We Handle Everything",
    "benefits.subtitle": "From your first question to your first day of class — and beyond.",
    "benefits.section.title": "Why Choose EduPath?",
    "benefits.section.subtitle": "We provide comprehensive support throughout your entire admission journey",
    "benefits.fast.title": "Fast Admission Process",
    "benefits.fast.desc": "Average 3-6 months from application to admission decision",
    "benefits.verified.title": "Verified Universities",
    "benefits.verified.desc": "All universities are accredited and internationally recognized",
    "benefits.expert.title": "Expert Guidance",
    "benefits.expert.desc": "1-on-1 support from experienced admission advisors",
    "benefits.success.title": "89% Success Rate",
    "benefits.success.desc": "Our proven methodology ensures maximum admission chances",
    "benefits.support.title": "24/7 Support",
    "benefits.support.desc": "Always available for your questions and concerns",
    "benefits.cities.title": "Multi-City Presence",
    "benefits.cities.desc": "Offices in Astana, Almaty, and online support",
    "benefits.docs.title": "Document Preparation",
    "benefits.docs.desc": "We prepare and verify every document required for your application.",
    "benefits.visa.title": "Visa Support",
    "benefits.visa.desc": "Full guidance through the student visa process from start to finish.",
    "benefits.dorm.title": "Dormitory Arrangement",
    "benefits.dorm.desc": "We arrange your accommodation before you even land.",
    "benefits.life.title": "Life Setup",
    "benefits.life.desc": "SIM card, bank account, city orientation — we cover the essentials.",

    // Universities section
    "unis.title": "Popular Universities",
    "unis.subtitle": "Curated selection of Kazakhstan's top academic institutions.",
    "unis.viewAll": "View All Universities",
    "unis.viewCard": "View Details",
    "unis.apply": "Apply",
    "unis.from": "Starting from",
    "unis.topPick": "Top Pick",

    // How It Works
    "how.badge": "How It Works",
    "how.title": "Three Steps to Your University",
    "how.step1.title": "Free Consultation",
    "how.step1.desc": "Tell us your goals. We match you with the right university and programme.",
    "how.step2.title": "We Handle the Process",
    "how.step2.desc": "Documents, visa, dormitory — our team manages everything on your behalf.",
    "how.step3.title": "Arrive & Study",
    "how.step3.desc": "Land in Kazakhstan with everything sorted. We help you settle in.",

    // Path to Success
    "path.title": "The Path to Success",
    "path.subtitle": "Five steps to your Kazakhstani academic journey.",
    "path.step1.title": "Select",
    "path.step1.desc": "Choose from 100+ English programs.",
    "path.step2.title": "Apply",
    "path.step2.desc": "Direct application portal for all unis.",
    "path.step3.title": "Documents",
    "path.step3.desc": "Secure verification and translation help.",
    "path.step4.title": "Visa/IIN",
    "path.step4.desc": "Full legal and migration support.",
    "path.step5.title": "Arrival",
    "path.step5.desc": "Airport pickup and dorm check-in.",

    // Services page
    "services.badge": "Our Services",
    "services.title": "Everything Handled for You",
    "services.subtitle": "We take the entire process off your shoulders — from the first form to the first day of class.",
    "services.problem": "The Problem",
    "services.solution": "Our Solution",
    "services.cta": "Get Free Consultation",

    // About page
    "about.badge": "About Us",
    "about.title": "Empowering Students to Achieve Their Dreams",
    "about.subtitle": "EduPath Kazakhstan is dedicated to helping aspiring students navigate their journey to world-class education.",
    "about.story.title": "Our Story",
    "about.mission.title": "Our Mission",
    "about.vision.title": "Our Vision",
    "about.values.title": "Our Values",
    "about.partners.title": "Our Partner Universities",
    "about.partners.subtitle": "We have signed agreements with leading universities across Kazakhstan.",
    "about.why.title": "Why Choose EduPath?",
    "about.cta.title": "Ready to Start Your Journey?",
    "about.cta.subtitle": "Schedule a free consultation today.",
    "about.cta.button": "Book Free Consultation",
    "about.mission.desc": "To make quality education in Kazakhstan accessible to every aspiring student, regardless of their background or location.",
    "about.vision.desc": "A world where distance and circumstance don't determine destiny — where every student can access their dream education.",
    "about.values.desc": "Integrity, student-centeredness, excellence, and accessibility guide everything we do.",
    "about.story.p1": "EduPath Kazakhstan was born out of a simple observation: the gap between a student's ambition and the bureaucratic reality of enrolling in a foreign university is enormous. Paperwork, visa appointments, dormitory registration, bank account requirements — each step is a potential obstacle that stops talented people before they even arrive on campus.",
    "about.story.p2": "We started as a small team of education enthusiasts who had personally experienced — or watched friends experience — the frustration of receiving a university acceptance letter only to get lost in a maze of administrative steps. We decided to fix that.",
    "about.story.p3": "Today EduPath is a full-cycle educational agency focused entirely on Kazakhstan. We have built direct relationships with universities in Almaty and Astana, and we guide every student from their very first question all the way through to settling into their new city.",
    "about.story.p4": "We specialize in helping students enroll on a paid tuition basis with complete, end-to-end support. From choosing the right university and program to handling all documents, visa applications, and accommodation — we manage the entire admission journey so you can focus on what matters most: your education.",
    "about.story.p5": "Our philosophy is straightforward: a student should only have to think about studying. Everything else is on us.",
    "about.whychoose.experts.title": "Expert Advisors",
    "about.whychoose.experts.desc": "Our team includes former university admissions officers and education specialists with decades of combined experience.",
    "about.whychoose.personal.title": "Personalized Approach",
    "about.whychoose.personal.desc": "We don't believe in one-size-fits-all solutions. Every student gets a customized roadmap to success.",
    "about.whychoose.support.title": "24/7 Support",
    "about.whychoose.support.desc": "Your success is our priority. We're here to support you every step of your journey.",

    // Contact page
    "contact.badge": "Contact Us",
    "contact.title": "Get in Touch",
    "contact.subtitle": "We respond within one business day. Choose the type of inquiry below to get the right form.",
    "contact.subjectLabel": "Type of Inquiry",
    "contact.consultation": "General Consultation",
    "contact.partnership": "Partnership",
    "contact.name": "Full Name",
    "contact.namePlaceholder": "Your name",
    "contact.email": "Email Address",
    "contact.emailPlaceholder": "your@email.com",
    "contact.companyEmailPlaceholder": "your@company.com",
    "contact.phone": "Phone Number",
    "contact.phonePlaceholder": "+7 (700) 123-45-67 (WhatsApp)",
    "contact.phoneHint": "Use the number where you have WhatsApp — we may reach out there.",
    "contact.phoneHintShort": "Preferred: a number with WhatsApp.",
    "contact.country": "Country of Residence",
    "contact.countryPlaceholder": "e.g. Nigeria, India, Egypt",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Tell us about your goals, current education level, preferred field of study...",
    "contact.companyCountry": "Country",
    "contact.companyCountryPlaceholder": "Country where your company operates",
    "contact.companyName": "Company / Organisation Name",
    "contact.companyNamePlaceholder": "Company name",
    "contact.companyAbout": "About Your Company",
    "contact.companyAboutPlaceholder": "Brief description of what your company does...",
    "contact.consultationGoal": "Goal of this Consultation",
    "contact.consultationGoalPlaceholder": "What would you like to achieve through a partnership with EduPath?",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.sent": "Thank you for reaching out. We'll get back to you within one business day.",
    "contact.successTitle": "Message Sent!",
    "contact.wishlistIncluded": "Universities in your wishlist (will be included)",
    "contact.phoneLabel": "Phone",
    "contact.phoneHours": "Mon–Fri, 9 AM – 6 PM",
    "contact.whatsappAvailable": "WhatsApp available",
    "contact.emailLabel": "Email",
    "contact.emailResponse": "We respond within 24 hours",
    "contact.faqTitle": "Frequently Asked Questions",
    "contact.faqSubtitle": "Quick answers to common questions.",
    "contact.viewFaqs": "View FAQs",
    "contact.hideFaqs": "Hide FAQs",
    "contact.bookConsultation": "Book Consultation",
    "contact.faq1.question": "How much does your service cost?",
    "contact.faq1.answer": "Our initial consultation is completely free. Service fees depend on the scope of support required — we discuss and agree on everything transparently before you commit.",
    "contact.faq2.question": "How long does the admission process take?",
    "contact.faq2.answer": "Typically 2–4 months from initial consultation to receiving your admission letter, depending on the university and how quickly your documents are ready.",
    "contact.faq3.question": "Do you guarantee admission?",
    "contact.faq3.answer": "While no agency can guarantee admission, our thorough preparation ensures maximum chances. We provide honest assessments from the start.",
    "contact.faq4.question": "What support do you provide after I arrive?",
    "contact.faq4.answer": "We help with dormitory registration, bank account opening, SIM card setup, and any practical task you encounter during your studies.",

    // Universities listing page
    "unilist.title": "All Universities",
    "unilist.subtitle": "Explore and filter Kazakhstan's top universities.",
    "unilist.search": "Search universities...",
    "unilist.filters": "Filters",
    "unilist.clearFilters": "Clear Filters",
    "unilist.sortBy": "Sort by",
    "unilist.popular": "Most Popular",
    "unilist.priceLow": "Price: Low to High",
    "unilist.priceHigh": "Price: High to Low",
    "unilist.ratingHigh": "Top Rated",
    "unilist.location": "City",
    "unilist.allCities": "All Cities",
    "unilist.dormAvailable": "Dormitory Available",
    "unilist.topRated": "Top Rated Only (4.7+)",
    "unilist.field": "Field of Study",
    "unilist.language": "Language",
    "unilist.noResults": "No universities match your filters.",
    "unilist.clearAll": "Clear All Filters",

    // Wishlist page
    "wishlist.title": "My University Wishlist",
    "wishlist.empty": "Your wishlist is empty",
    "wishlist.emptyDesc": "Browse universities and click the bag icon to save them here.",
    "wishlist.browse": "Browse Universities",
    "wishlist.clearAll": "Clear all",
    "wishlist.view": "View",
    "wishlist.readyTitle": "Ready to apply?",
    "wishlist.readyDesc": "Submit a free consultation request — your saved universities will be included automatically.",
    "wishlist.applyBtn": "Apply for These Universities",

    // Footer
    "footer.stayUpdated": "Stay Updated",
    "footer.stayDesc": "Get the latest news on university openings, visa changes, and student life in Kazakhstan.",
    "footer.subscribe": "Subscribe",
    "footer.subscribed": "You're subscribed!",
    "footer.emailPlaceholder": "Your email address",
    "footer.navigation": "Navigation",
    "footer.resources": "Resources",
    "footer.aboutUs": "About Us",
    "footer.privacyPolicy": "Privacy Policy",
    "footer.contactSupport": "Contact Support",
    "footer.universityPartners": "University Partners",
    "footer.studentVisas": "Student Visas",
    "footer.scholarshipGuide": "Scholarship Guide",
    "footer.rights": "All rights reserved.",
  },

  ru: {
    // Nav
    "nav.universities": "Университеты",
    "nav.services": "Услуги",
    "nav.about": "О нас",
    "nav.contact": "Контакты",
    "nav.cart": "Список",

    // Hero
    "hero.badge": "Ваш путь в Казахстан",
    "hero.title1": "Учёба в",
    "hero.title2": "Казахстане",
    "hero.subtitle": "Мы берём на себя всё — поступление, визу, общежитие и обустройство в новом городе. Вы просто учитесь.",
    "hero.apply": "Подать заявку бесплатно",
    "hero.learnMore": "Узнать больше",

    // Trust
    "trust.partner": "Официальные партнёры университетов",
    "trust.support": "Полная поддержка — от визы до общежития",
    "trust.consultation": "Бесплатная консультация",
    "trust.process": "Процесс под ключ",

    // Why Kazakhstan
    "whykz.badge": "Почему Казахстан?",
    "whykz.title": "Умный выбор для иностранных студентов",
    "whykz.subtitle": "Доступные, признанные во всём мире дипломы с обучением на английском языке.",
    "whykz.section.title": "Почему учиться в Казахстане?",
    "whykz.section.subtitle": "Сочетание первоклассного образования и захватывающей центральноазиатской культуры по доступной цене.",
    "whykz.international.title": "Международное признание",
    "whykz.international.desc": "Дипломы признаются по всему миру благодаря Болонскому процессу, открывая двери к карьере в Европе, Азии и за их пределами.",
    "whykz.affordable.title": "Доступное обучение",
    "whykz.affordable.desc": "Качественное образование от $2,000/год. Высокий уровень жизни вдвое дешевле, чем в западных университетах.",
    "whykz.english.title": "Программы на английском",
    "whykz.english.desc": "Никакого языкового барьера. Сотни программ на английском в сферах IT, медицины и бизнеса.",
    "whykz.vibrant.title": "Яркая студенческая жизнь",
    "whykz.vibrant.desc": "От горнолыжных курортов Алматы до футуристической архитектуры Астаны. Настоящий глобальный студенческий хаб.",
    "whykz.safe.title": "Безопасно и гостеприимно",
    "whykz.safe.desc": "Казахстан стабильно входит в число самых безопасных стран для иностранных студентов в Центральной Азии.",
    "whykz.career.title": "Карьерные возможности",
    "whykz.career.desc": "Растущая экономика и активная стартап-сцена открывают реальные перспективы после окончания учёбы.",

    // Benefits
    "benefits.badge": "Почему EduPath?",
    "benefits.title": "Мы берём на себя всё",
    "benefits.subtitle": "От первого вопроса до первого дня занятий — и дальше.",
    "benefits.section.title": "Почему выбирают EduPath?",
    "benefits.section.subtitle": "Мы обеспечиваем полную поддержку на всём пути поступления",
    "benefits.fast.title": "Быстрое поступление",
    "benefits.fast.desc": "В среднем 3-6 месяцев от подачи заявки до решения о зачислении",
    "benefits.verified.title": "Проверенные университеты",
    "benefits.verified.desc": "Все университеты аккредитованы и признаны на международном уровне",
    "benefits.expert.title": "Экспертное сопровождение",
    "benefits.expert.desc": "Персональная поддержка от опытных консультантов по поступлению",
    "benefits.success.title": "89% успешных поступлений",
    "benefits.success.desc": "Наша проверенная методология обеспечивает максимальные шансы на зачисление",
    "benefits.support.title": "Поддержка 24/7",
    "benefits.support.desc": "Всегда на связи для ваших вопросов и консультаций",
    "benefits.cities.title": "Присутствие в нескольких городах",
    "benefits.cities.desc": "Офисы в Астане, Алматы и онлайн-поддержка",
    "benefits.docs.title": "Подготовка документов",
    "benefits.docs.desc": "Мы готовим и проверяем все документы для поступления.",
    "benefits.visa.title": "Поддержка по визе",
    "benefits.visa.desc": "Полное сопровождение оформления студенческой визы.",
    "benefits.dorm.title": "Устройство в общежитие",
    "benefits.dorm.desc": "Мы бронируем жильё ещё до вашего приезда.",
    "benefits.life.title": "Обустройство жизни",
    "benefits.life.desc": "SIM-карта, банковский счёт, ориентация по городу — всё включено.",

    // Universities section
    "unis.title": "Популярные университеты",
    "unis.subtitle": "Отборные ведущие учебные заведения Казахстана.",
    "unis.viewAll": "Все университеты",
    "unis.viewCard": "Подробнее",
    "unis.apply": "Подать заявку",
    "unis.from": "От",
    "unis.topPick": "Топ выбор",

    // How It Works
    "how.badge": "Как это работает",
    "how.title": "Три шага до вашего университета",
    "how.step1.title": "Бесплатная консультация",
    "how.step1.desc": "Расскажите о своих целях. Мы подберём подходящий университет и программу.",
    "how.step2.title": "Мы ведём процесс",
    "how.step2.desc": "Документы, виза, общежитие — наша команда управляет всем.",
    "how.step3.title": "Приезжайте и учитесь",
    "how.step3.desc": "Прилетайте в Казахстан с готовым решением всех вопросов. Мы поможем обустроиться.",

    // Path to Success
    "path.title": "Путь к успеху",
    "path.subtitle": "Пять шагов к вашему академическому путешествию в Казахстане.",
    "path.step1.title": "Выбор",
    "path.step1.desc": "Выберите из 100+ программ на английском.",
    "path.step2.title": "Заявка",
    "path.step2.desc": "Прямая подача заявки во все университеты.",
    "path.step3.title": "Документы",
    "path.step3.desc": "Безопасная верификация и помощь с переводом.",
    "path.step4.title": "Виза/ИИН",
    "path.step4.desc": "Полная юридическая и миграционная поддержка.",
    "path.step5.title": "Приезд",
    "path.step5.desc": "Встреча в аэропорту и заселение в общежитие.",

    // Services
    "services.badge": "Наши услуги",
    "services.title": "Всё под ключ",
    "services.subtitle": "Мы полностью берём процесс на себя — от первой формы до первого дня занятий.",
    "services.problem": "Проблема",
    "services.solution": "Наше решение",
    "services.cta": "Получить консультацию",

    // About
    "about.badge": "О нас",
    "about.title": "Помогаем студентам достичь мечты",
    "about.subtitle": "EduPath Kazakhstan помогает студентам пройти путь к качественному образованию в Казахстане.",
    "about.story.title": "Наша история",
    "about.mission.title": "Наша миссия",
    "about.vision.title": "Наше видение",
    "about.values.title": "Наши ценности",
    "about.partners.title": "Университеты-партнёры",
    "about.partners.subtitle": "Мы заключили соглашения с ведущими университетами по всему Казахстану.",
    "about.why.title": "Почему EduPath?",
    "about.cta.title": "Готовы начать?",
    "about.cta.subtitle": "Запишитесь на бесплатную консультацию прямо сейчас.",
    "about.cta.button": "Записаться на консультацию",
    "about.mission.desc": "Сделать качественное образование в Казахстане доступным для каждого целеустремлённого студента, независимо от его происхождения или местоположения.",
    "about.vision.desc": "Мир, где расстояние и обстоятельства не определяют судьбу — где каждый студент может получить образование своей мечты.",
    "about.values.desc": "Честность, ориентация на студента, стремление к совершенству и доступность — вот наши главные принципы.",
    "about.story.p1": "EduPath Kazakhstan появился из простого наблюдения: между амбициями студента и бюрократической реальностью поступления в иностранный университет — огромная пропасть. Документы, визовые встречи, регистрация в общежитии, банковские требования — каждый шаг потенциально останавливает талантливых людей ещё до того, как они попадут в кампус.",
    "about.story.p2": "Мы начинали как небольшая команда энтузиастов образования, которые лично пережили — или наблюдали у друзей — разочарование от получения письма о зачислении, после которого человек терялся в лабиринте административных шагов. Мы решили это исправить.",
    "about.story.p3": "Сегодня EduPath — это образовательное агентство полного цикла, специализирующееся исключительно на Казахстане. Мы выстроили прямые связи с университетами Алматы и Астаны и сопровождаем каждого студента от первого вопроса до обустройства в новом городе.",
    "about.story.p4": "Мы специализируемся на помощи студентам с поступлением на платной основе с полным сопровождением от начала до конца. От выбора подходящего университета и программы до оформления всех документов, визы и жилья — мы ведём весь процесс поступления, чтобы вы могли сосредоточиться на главном: вашем образовании.",
    "about.story.p5": "Наша философия проста: студент должен думать только об учёбе. Всё остальное — наша забота.",
    "about.whychoose.experts.title": "Опытные консультанты",
    "about.whychoose.experts.desc": "В нашей команде — бывшие сотрудники приёмных комиссий и специалисты по образованию с многолетним опытом.",
    "about.whychoose.personal.title": "Индивидуальный подход",
    "about.whychoose.personal.desc": "Мы не верим в универсальные решения. Каждый студент получает персональную дорожную карту к успеху.",
    "about.whychoose.support.title": "Поддержка 24/7",
    "about.whychoose.support.desc": "Ваш успех — наш приоритет. Мы рядом на каждом шаге вашего пути.",

    // Contact
    "contact.badge": "Свяжитесь с нами",
    "contact.title": "Связаться с нами",
    "contact.subtitle": "Мы отвечаем в течение одного рабочего дня. Выберите тип запроса ниже.",
    "contact.subjectLabel": "Тип запроса",
    "contact.consultation": "Общая консультация",
    "contact.partnership": "Партнёрство",
    "contact.name": "Полное имя",
    "contact.namePlaceholder": "Ваше имя",
    "contact.email": "Электронная почта",
    "contact.emailPlaceholder": "ваш@email.com",
    "contact.companyEmailPlaceholder": "ваш@компания.com",
    "contact.phone": "Номер телефона",
    "contact.phonePlaceholder": "+7 (700) 123-45-67 (WhatsApp)",
    "contact.phoneHint": "Укажите номер с WhatsApp — мы можем связаться там.",
    "contact.phoneHintShort": "Предпочтительно: номер с WhatsApp.",
    "contact.country": "Страна проживания",
    "contact.countryPlaceholder": "например, Нигерия, Индия, Египет",
    "contact.message": "Сообщение",
    "contact.messagePlaceholder": "Расскажите о своих целях, текущем уровне образования, предпочтительной области обучения...",
    "contact.companyCountry": "Страна",
    "contact.companyCountryPlaceholder": "Страна, где работает ваша компания",
    "contact.companyName": "Название компании / организации",
    "contact.companyNamePlaceholder": "Название компании",
    "contact.companyAbout": "О вашей компании",
    "contact.companyAboutPlaceholder": "Краткое описание деятельности вашей компании...",
    "contact.consultationGoal": "Цель консультации",
    "contact.consultationGoalPlaceholder": "Чего вы хотите достичь через партнёрство с EduPath?",
    "contact.send": "Отправить сообщение",
    "contact.sending": "Отправка...",
    "contact.sent": "Спасибо за обращение. Мы свяжемся с вами в течение одного рабочего дня.",
    "contact.successTitle": "Сообщение отправлено!",
    "contact.wishlistIncluded": "Университеты в вашем списке (будут включены)",
    "contact.phoneLabel": "Телефон",
    "contact.phoneHours": "Пн–Пт, 9:00 – 18:00",
    "contact.whatsappAvailable": "WhatsApp доступен",
    "contact.emailLabel": "Email",
    "contact.emailResponse": "Отвечаем в течение 24 часов",
    "contact.faqTitle": "Часто задаваемые вопросы",
    "contact.faqSubtitle": "Быстрые ответы на частые вопросы.",
    "contact.viewFaqs": "Показать FAQ",
    "contact.hideFaqs": "Скрыть FAQ",
    "contact.bookConsultation": "Записаться на консультацию",
    "contact.faq1.question": "Сколько стоят ваши услуги?",
    "contact.faq1.answer": "Первичная консультация полностью бесплатна. Стоимость услуг зависит от объёма необходимой поддержки — мы обсуждаем и согласовываем всё прозрачно до начала работы.",
    "contact.faq2.question": "Сколько времени занимает процесс поступления?",
    "contact.faq2.answer": "Обычно 2–4 месяца от первичной консультации до получения письма о зачислении, в зависимости от университета и готовности ваших документов.",
    "contact.faq3.question": "Гарантируете ли вы поступление?",
    "contact.faq3.answer": "Ни одно агентство не может гарантировать поступление, но наша тщательная подготовка обеспечивает максимальные шансы. Мы даём честную оценку с самого начала.",
    "contact.faq4.question": "Какую поддержку вы оказываете после приезда?",
    "contact.faq4.answer": "Мы помогаем с регистрацией в общежитии, открытием банковского счёта, получением SIM-карты и любыми практическими задачами во время учёбы.",

    // Universities listing
    "unilist.title": "Все университеты",
    "unilist.subtitle": "Изучайте и фильтруйте ведущие университеты Казахстана.",
    "unilist.search": "Поиск университетов...",
    "unilist.filters": "Фильтры",
    "unilist.clearFilters": "Сбросить",
    "unilist.sortBy": "Сортировка",
    "unilist.popular": "Популярные",
    "unilist.priceLow": "Цена: от дешёвых",
    "unilist.priceHigh": "Цена: от дорогих",
    "unilist.ratingHigh": "По рейтингу",
    "unilist.location": "Город",
    "unilist.allCities": "Все города",
    "unilist.dormAvailable": "Есть общежитие",
    "unilist.topRated": "Только топ (4.7+)",
    "unilist.field": "Направление",
    "unilist.language": "Язык обучения",
    "unilist.noResults": "Нет университетов по вашим фильтрам.",
    "unilist.clearAll": "Сбросить фильтры",

    // Wishlist
    "wishlist.title": "Мой список университетов",
    "wishlist.empty": "Список пуст",
    "wishlist.emptyDesc": "Просматривайте университеты и сохраняйте их, нажав на значок корзины.",
    "wishlist.browse": "Смотреть университеты",
    "wishlist.clearAll": "Очистить всё",
    "wishlist.view": "Смотреть",
    "wishlist.readyTitle": "Готовы подать заявку?",
    "wishlist.readyDesc": "Отправьте запрос — сохранённые университеты будут включены автоматически.",
    "wishlist.applyBtn": "Подать заявку",

    // Footer
    "footer.stayUpdated": "Будьте в курсе",
    "footer.stayDesc": "Последние новости об открытии поступлений, изменениях в визах и студенческой жизни.",
    "footer.subscribe": "Подписаться",
    "footer.subscribed": "Вы подписаны!",
    "footer.emailPlaceholder": "Ваш email",
    "footer.navigation": "Навигация",
    "footer.resources": "Ресурсы",
    "footer.aboutUs": "О компании",
    "footer.privacyPolicy": "Политика конфиденциальности",
    "footer.contactSupport": "Поддержка",
    "footer.universityPartners": "Университеты-партнёры",
    "footer.studentVisas": "Студенческие визы",
    "footer.scholarshipGuide": "Гиды по стипендиям",
    "footer.rights": "Все права защищены.",
  },

  kz: {
    // Nav
    "nav.universities": "Университеттер",
    "nav.services": "Қызметтер",
    "nav.about": "Біз туралы",
    "nav.contact": "Байланыс",
    "nav.cart": "Тізім",

    // Hero
    "hero.badge": "Қазақстанға шлюзіңіз",
    "hero.title1": "Оқу орны —",
    "hero.title2": "Қазақстан",
    "hero.subtitle": "Біз барлығын өз мойнымызға аламыз — қабылдану, виза, жатақхана және жаңа қалаға бейімделу. Сіз тек оқисыз.",
    "hero.apply": "Тегін өтінім беру",
    "hero.learnMore": "Толығырақ",

    // Trust
    "trust.partner": "Ресми университет серіктестері",
    "trust.support": "Толық қолдау — визадан жатақханаға дейін",
    "trust.consultation": "Тегін кеңес",
    "trust.process": "Толық процесс",

    // Why Kazakhstan
    "whykz.badge": "Неге Қазақстан?",
    "whykz.title": "Шетелдік студенттер үшін ақылды таңдау",
    "whykz.subtitle": "Ағылшын тілінде оқытылатын, әлемде танылған дипломдар — қолжетімді бағада.",
    "whykz.section.title": "Неге Қазақстанда оқу керек?",
    "whykz.section.subtitle": "Әлемдік деңгейдегі білім мен тамаша Орталық Азия мәдениетінің үйлесімін қолжетімді бағада сезініңіз.",
    "whykz.international.title": "Халықаралық мойындау",
    "whykz.international.desc": "Болон процесі арқылы дипломдар бүкіл әлемде танылады, Еуропа, Азия және одан тыс жерлерде мансап есіктерін ашады.",
    "whykz.affordable.title": "Қолжетімді оқу ақысы",
    "whykz.affordable.desc": "Сапалы білім жылына $2,000-дан басталады. Батыс университеттеріне қарағанда екі есе арзан өмір сүру деңгейі.",
    "whykz.english.title": "Ағылшын тіліндегі бағдарламалар",
    "whykz.english.desc": "Т��л кедергісі жоқ. IT, медицина және бизнес саласында ағылшын тілінде жүздеген бағдарламалар бар.",
    "whykz.vibrant.title": "Жарқын студенттік өмір",
    "whykz.vibrant.desc": "Алматының тау шаңғысы курорттарынан Астананың футуристік сәулетіне дейін. Шынайы жаһандық студенттер хабы.",
    "whykz.safe.title": "Қауіпсіз және қонақжай",
    "whykz.safe.desc": "Қазақстан Орталық Азиядағы шетелдік студенттерге ең қауіпсіз ел ретінде бағаланады.",
    "whykz.career.title": "Мансаптық мүмкіндіктер",
    "whykz.career.desc": "Өсіп келе жатқан экономика және стартап экожүйесі бітірушілерге нақты перспектива ашады.",

    // Benefits
    "benefits.badge": "Неге EduPath?",
    "benefits.title": "Барлығын өз мойнымызға аламыз",
    "benefits.subtitle": "Алғашқы сұрақтан оқудың алғашқы күніне дейін — және одан әрі.",
    "benefits.section.title": "Неге EduPath таңдайды?",
    "benefits.section.subtitle": "Біз бүкіл қабылдау жолында толық қолдау көрсетеміз",
    "benefits.fast.title": "Жылдам қабылдау процесі",
    "benefits.fast.desc": "Өтініш беруден қабылдау шешіміне дейін орташа 3-6 ай",
    "benefits.verified.title": "Тексерілген университеттер",
    "benefits.verified.desc": "Барлық университеттер аккредиттелген және халықаралық деңгейде танылған",
    "benefits.expert.title": "Сарапшылық нұсқау",
    "benefits.expert.desc": "Тәжірибелі қабылдау кеңесшілерінің жеке қолдауы",
    "benefits.success.title": "89% табысты қабылдау",
    "benefits.success.desc": "Біздің дәлелденген әдістемеміз қабылдану мүмкіндігін барынша арттырады",
    "benefits.support.title": "24/7 қолдау",
    "benefits.support.desc": "Сұрақтарыңыз бен алаңдаушылықтарыңыз үшін әрқашан қол жетімді",
    "benefits.cities.title": "Бірнеше қалада қатысу",
    "benefits.cities.desc": "Астана, Алматыда кеңселер және онлайн қолдау",
    "benefits.docs.title": "Құжаттарды дайындау",
    "benefits.docs.desc": "Өтінім үшін қажетті барлық құжаттарды дайындап, тексереміз.",
    "benefits.visa.title": "Виза қолдауы",
    "benefits.visa.desc": "Студенттік визаны ресімдеу процесінде толық нұсқаулық.",
    "benefits.dorm.title": "Жатақхана орналастыру",
    "benefits.dorm.desc": "Сіз келмес бұрын тұрғын үй мәселесін шешеміз.",
    "benefits.life.title": "Тұрмысты реттеу",
    "benefits.life.desc": "SIM-карта, банктік шот, қала бойынша бағдарлау — бәрі біздің жауапкершілігімізде.",

    // Universities section
    "unis.title": "Танымал университеттер",
    "unis.subtitle": "Қазақстанның үздік оқу орындарының іріктелген тізімі.",
    "unis.viewAll": "Барлық университеттер",
    "unis.viewCard": "Толығырақ",
    "unis.apply": "Өтінім беру",
    "unis.from": "Бастап",
    "unis.topPick": "Үздік таңдау",

    // How It Works
    "how.badge": "Қалай жұмыс істейді",
    "how.title": "Университетке дейін үш қадам",
    "how.step1.title": "Тегін кеңес",
    "how.step1.desc": "Мақсаттарыңызды айтыңыз. Біз сізге дұрыс университет пен бағдарлама ұсынамыз.",
    "how.step2.title": "Процесті басқарамыз",
    "how.step2.desc": "Құжаттар, виза, жатақхана — командамыз барлығын өз мойнына алады.",
    "how.step3.title": "Келіңіз және оқыңыз",
    "how.step3.desc": "Барлық мәселе шешілген күйде Қазақстанға келіңіз. Бейімделуге көмектесеміз.",

    // Path to Success
    "path.title": "Табысқа жол",
    "path.subtitle": "Қазақстандағы академиялық сапарыңызға бес қадам.",
    "path.step1.title": "Таңдау",
    "path.step1.desc": "100+ ағылшын тіліндегі бағдарламадан таңдаңыз.",
    "path.step2.title": "Өтінім",
    "path.step2.desc": "Барлық университеттерге тікелей өтінім беру.",
    "path.step3.title": "Құжаттар",
    "path.step3.desc": "Қауіпсіз тексеру және аударма көмегі.",
    "path.step4.title": "Виза/ЖСН",
    "path.step4.desc": "Толық заңдық және көші-қон қолдауы.",
    "path.step5.title": "Келу",
    "path.step5.desc": "Әуежайдан кездесу және жатақханаға орналастыру.",

    // Services
    "services.badge": "Қызметтеріміз",
    "services.title": "Барлығы біздің жауапкершілігімізде",
    "services.subtitle": "Алғашқы формадан оқудың алғашқы күніне дейін процесті толығымен өз мойнымызға аламыз.",
    "services.problem": "Мәселе",
    "services.solution": "Біздің шешім",
    "services.cta": "Тегін кеңес алу",

    // About
    "about.badge": "Біз туралы",
    "about.title": "Студенттерге армандарына жетуге көмектесеміз",
    "about.subtitle": "EduPath Kazakhstan студенттерге Қазақстандағы үздік білімге жету жолын бастан-аяқ сүйемелдейді.",
    "about.story.title": "Біздің тарих",
    "about.mission.title": "Миссиямыз",
    "about.vision.title": "Болашақ жоспарымыз",
    "about.values.title": "Құндылықтарымыз",
    "about.partners.title": "Серіктес университеттер",
    "about.partners.subtitle": "Қазақстанның жетекші университеттерімен келісімдер жасадық.",
    "about.why.title": "Неге EduPath?",
    "about.cta.title": "Сапарды бастауға дайынсыз ба?",
    "about.cta.subtitle": "Бүгін тегін кеңесшіге жазылыңыз.",
    "about.cta.button": "Тегін кеңес алу",
    "about.mission.desc": "Қазақстандағы сапалы білімді әр мақсатшыл студентке қолжетімді ету — шығу тегіне немесе орналасқан жеріне қарамастан.",
    "about.vision.desc": "Қашықтық пен жағдай тағдырды анықтамайтын әлем — әр студент арманындағы білімге қол жеткізе алатын орта.",
    "about.values.desc": "Адалдық, студентке бағдарлану, жетілдіруге ұмтылу және қолжетімділік — біздің негізгі қағидаларымыз.",
    "about.story.p1": "EduPath Kazakhstan қарапайым бақылаудан туындады: студенттің арманы мен шетелдік университетке түсудің бюрократиялық шындығы арасындағы алшақтық өте үлкен. Құжаттар, виза кездесулері, жатақханаға тіркелу, банктік талаптар — әрбір қадам талантты адамдарды кампусқа жетпей-ақ тоқтатуы мүмкін.",
    "about.story.p2": "Біз қабылдау туралы хат алғаннан кейін әкімшілік қадамдар лабиринтінде адасып қалудың күйзелісін өз басынан өткерген немесе достарынан көрген білім беру энтузиастарының кішкентай командасы ретінде бастадық. Біз мұны түзетуге шештік.",
    "about.story.p3": "Бүгінгі таңда EduPath — Қазақстанға толығымен бағытталған толық циклді білім агенттігі. Біз Алматы мен Астана университеттерімен тікелей байланыс орнаттық және әр студентті алғашқы сұрағынан жаңа қаласында орналасқанға дейін сүйемелдейміз.",
    "about.story.p4": "Біз студенттерге ақылы негізде оқуға түсуге толық сүйемелдеумен көмектесуге маманданамыз. Дұрыс университет пен бағдарламаны таңдаудан бастап барлық құжаттарды, визаны және тұрғын үйді ресімдеуге дейін — біз бүкіл қабылдау процесін басқарамыз, сіз ең маңыздыға назар аударуыңыз үшін: білім алу.",
    "about.story.p5": "Біздің философиямыз қарапайым: студент тек оқу туралы ойлауы керек. Қалғанының бәрі — біздің міндетіміз.",
    "about.whychoose.experts.title": "Тәжірибелі кеңесшілер",
    "about.whychoose.experts.desc": "Біздің командада — бұрынғы қабылдау комиссияларының қызметкерлері және көп жылдық тәжірибесі бар білім мамандары бар.",
    "about.whychoose.personal.title": "Жеке көзқарас",
    "about.whychoose.personal.desc": "Біз бір өлшемді шешімдерге сенбейміз. Әр студент табысқа жетудің жеке жол картасын алады.",
    "about.whychoose.support.title": "24/7 қолдау",
    "about.whychoose.support.desc": "Сіздің табысыңыз — біздің басымдығымыз. Біз жолыңыздың әр қадамында сізбен біргеміз.",

    // Contact
    "contact.badge": "Бізбен байланыс",
    "contact.title": "Бізбен байланысыңыз",
    "contact.subtitle": "Біз бір жұмыс күні ішінде жауап береміз. Төменде сұраныс түрін таңдаңыз.",
    "contact.subjectLabel": "Сұраныс түрі",
    "contact.consultation": "Жалпы кеңес",
    "contact.partnership": "Серіктестік",
    "contact.name": "Толық аты-жөні",
    "contact.namePlaceholder": "Сіздің атыңыз",
    "contact.email": "Электрондық пошта",
    "contact.emailPlaceholder": "сіздің@email.com",
    "contact.companyEmailPlaceholder": "сіздің@компания.com",
    "contact.phone": "Телефон нөмірі",
    "contact.phonePlaceholder": "+7 (700) 123-45-67 (WhatsApp)",
    "contact.phoneHint": "WhatsApp бар нөмірді көрсетіңіз — онда хабарласуымыз мүмкін.",
    "contact.phoneHintShort": "Қалаулы: WhatsApp бар нөмір.",
    "contact.country": "Тұратын еліңіз",
    "contact.countryPlaceholder": "мысалы, Нигерия, Үндістан, Мысыр",
    "contact.message": "Хабарлама",
    "contact.messagePlaceholder": "Мақсаттарыңыз, қазіргі білім деңгейіңіз, қалаулы оқу саласы туралы айтыңыз...",
    "contact.companyCountry": "Ел",
    "contact.companyCountryPlaceholder": "Компанияңыз жұмыс істейтін ел",
    "contact.companyName": "Компания / ұйым атауы",
    "contact.companyNamePlaceholder": "Компания атауы",
    "contact.companyAbout": "Компанияңыз туралы",
    "contact.companyAboutPlaceholder": "Компанияңыздың қызметі туралы қысқаша сипаттама...",
    "contact.consultationGoal": "Кеңес мақсаты",
    "contact.consultationGoalPlaceholder": "EduPath-пен серіктестік арқылы нені қалайсыз?",
    "contact.send": "Хабарлама жіберу",
    "contact.sending": "Жіберілуде...",
    "contact.sent": "Хабарласқаныңызға рахмет. Біз бір жұмыс күні ішінде жауап береміз.",
    "contact.successTitle": "Хабарлама жіберілді!",
    "contact.wishlistIncluded": "Тізіміңіздегі университеттер (қосылады)",
    "contact.phoneLabel": "Телефон",
    "contact.phoneHours": "Дс–Жм, 9:00 – 18:00",
    "contact.whatsappAvailable": "WhatsApp қолжетімді",
    "contact.emailLabel": "Email",
    "contact.emailResponse": "24 сағат ішінде жауап береміз",
    "contact.faqTitle": "Жиі қойылатын сұрақтар",
    "contact.faqSubtitle": "Жиі сұрақтарға жылдам жауаптар.",
    "contact.viewFaqs": "FAQ көру",
    "contact.hideFaqs": "FAQ жасыру",
    "contact.bookConsultation": "Кеңеске жазылу",
    "contact.faq1.question": "Қызметтеріңіз қанша тұрады?",
    "contact.faq1.answer": "Алғашқы кеңес толығымен тегін. Қызмет құны қажетті қолдау көлеміне байланысты — жұмыс басталмас бұрын бәрін ашық талқылап, келісеміз.",
    "contact.faq2.question": "Қабылдау процесі қанша уақыт алады?",
    "contact.faq2.answer": "Әдетте алғашқы кеңестен қабылдау хатын алуға дейін 2-4 ай, университет пен құжаттарыңыздың дайындығына байланысты.",
    "contact.faq3.question": "Қабылдауға кепілдік бересіз бе?",
    "contact.faq3.answer": "Ешбір агенттік қабылдауға кепілдік бере алмайды, бірақ біздің мұқият дайындығымыз максималды мүмкіндіктерді қамтамасыз етеді. Бастапқыдан адал бағалау береміз.",
    "contact.faq4.question": "Келгеннен кейін қандай қолдау көрсетесіздер?",
    "contact.faq4.answer": "Жатақханаға тіркелу, банк шотын ашу, SIM-карта алу және оқу кезіндегі кез келген практикалық тапсырмаларға көмектесеміз.",

    // Universities listing
    "unilist.title": "Барлық университеттер",
    "unilist.subtitle": "Қазақстанның үздік университеттерін зерттеп, сүзіңіз.",
    "unilist.search": "Университет іздеу...",
    "unilist.filters": "Сүзгілер",
    "unilist.clearFilters": "Тазалау",
    "unilist.sortBy": "Сұрыптау",
    "unilist.popular": "Танымал",
    "unilist.priceLow": "Баға: арзаннан",
    "unilist.priceHigh": "Баға: қымбаттан",
    "unilist.ratingHigh": "Рейтинг бойынша",
    "unilist.location": "Қала",
    "unilist.allCities": "Барлық қалалар",
    "unilist.dormAvailable": "Жатақхана бар",
    "unilist.topRated": "Тек үздік (4.7+)",
    "unilist.field": "Оқу бағыты",
    "unilist.language": "Оқыту тілі",
    "unilist.noResults": "Сүзгілеріңізге сәйкес университет жоқ.",
    "unilist.clearAll": "Барлық сүзгіні тазалау",

    // Wishlist
    "wishlist.title": "Университеттер тізімім",
    "wishlist.empty": "Тізім бос",
    "wishlist.emptyDesc": "Университеттерді қараңыз және қалталы белгішені басып сақтаңыз.",
    "wishlist.browse": "Университеттерді қарау",
    "wishlist.clearAll": "Барлығын тазалау",
    "wishlist.view": "Қарау",
    "wishlist.readyTitle": "Өтінім беруге дайынсыз ба?",
    "wishlist.readyDesc": "Тегін кеңес сұраңыз — сақталған университеттер автоматты түрде қосылады.",
    "wishlist.applyBtn": "Өтінім беру",

    // Footer
    "footer.stayUpdated": "Жаңалықтарды алыңыз",
    "footer.stayDesc": "Университет ашылулары, виза өзгерістері және студенттік өмір туралы соңғы жаңалықтар.",
    "footer.subscribe": "Жазылу",
    "footer.subscribed": "Жазылдыңыз!",
    "footer.emailPlaceholder": "Сіздің email",
    "footer.navigation": "Навигация",
    "footer.resources": "Ресурстар",
    "footer.aboutUs": "Біз туралы",
    "footer.privacyPolicy": "Құпиялылық саясаты",
    "footer.contactSupport": "Қолдау қызметі",
    "footer.universityPartners": "Серіктес университеттер",
    "footer.studentVisas": "Студенттік визалар",
    "footer.scholarshipGuide": "Стипендия нұсқаулығы",
    "footer.rights": "Барлық құқықтар қорғалған.",
  },
}

const LangContext = createContext<LangContextType>({
  lang: "en",
  setLang: () => {},
  t: (k) => k,
})

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("en")
  const t = (key: string) => translations[lang][key] ?? translations["en"][key] ?? key
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
